# Generated by Django 4.2.11 on 2024-06-29 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_request_donors_donation'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='bloodunit',
            name='Donor',
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='blood_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='date_donated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
            preserve_default=False,
        ),
    ]
