# Generated by Django 4.2.11 on 2024-05-05 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_address_blood_unit_certificate_user_img_user_point_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requestor', to='patient.reciever'),
        ),
        migrations.AddField(
            model_name='blood_unit',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_unit_donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blood_unit',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_unit_requestor', to='patient.reciever'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
