# Generated by Django 4.2.11 on 2024-05-26 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_rename_doner_donor_donor_remove_donor_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='Donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
        migrations.AlterField(
            model_name='point',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
    ]
