# Generated by Django 4.2.11 on 2024-05-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_address_user_alter_bloodunit_donor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='home_town',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='place',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='dop',
            new_name='dob',
        ),
    ]
