# Generated by Django 4.2.11 on 2024-05-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_rename_home_town_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='pincode',
            new_name='postal_code',
        ),
    ]
