# Generated by Django 4.2.11 on 2024-05-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_rename_pincode_address_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='donor',
            new_name='user',
        ),
    ]
