# Generated by Django 4.2.11 on 2024-05-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_rename_donor_donor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='user',
            new_name='donor',
        ),
    ]
