# Generated by Django 4.2.11 on 2024-05-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_rename_user_donor_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='wieght',
            new_name='weight',
        ),
    ]
