# Generated by Django 4.2.11 on 2024-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('pic', models.ImageField(default='ads.jpeg', upload_to='News')),
                ('content', models.TextField()),
            ],
        ),
    ]
