# Generated by Django 4.2.11 on 2024-05-05 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0002_address_blood_unit_certificate_user_img_user_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('Hospital', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('blood_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.blood_unit')),
                ('donors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
                ('patient_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.address')),
                ('request_raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to='patient.reciever')),
            ],
        ),
    ]
