# Generated by Django 4.2.11 on 2024-06-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='donors',
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_donated', models.DateTimeField(auto_now_add=True)),
                ('approved_by_receiver', models.BooleanField(default=False)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.request')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
    ]
