# Generated by Django 4.2.11 on 2024-05-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciever',
            name='address',
        ),
    ]
