# Generated by Django 4.2.11 on 2024-05-25 02:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_user_phone_number'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciever',
            name='address',
            field=models.ForeignKey(default=datetime.datetime(2024, 5, 25, 2, 17, 25, 709580, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='donor.address'),
            preserve_default=False,
        ),
    ]
