# Generated by Django 4.2.11 on 2024-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_reciever_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciever',
            name='is_reciever',
            field=models.BooleanField(default=False),
        ),
    ]
